/*1  */
SELECT DISTINCT c.CODCARRERA, a.TANTOPORUNO FROM CARRERAS c, APUESTAS a
WHERE c.CODCARRERA = a.CODCARRERA AND a.TANTOPORUNO>3;

/*2*/
SELECT NOMBRE, APELLIDOS FROM PERSONAS
WHERE FECHA_NACIMIENTO>'31-12-1979' ORDER BY FECHA_NACIMIENTO DESC;

/*3*/
SELECT DISTINCT CODCABALLO FROM PARTICIPACIONES
WHERE POSICIONFINAL IN (1,2,3) ORDER BY CODCABALLO;

/*4*/
SELECT * FROM CARRERAS WHERE IMPORTEPREMIO > 50000;

/*5*/
SELECT NOMBRE, DNI FROM CLIENTES
WHERE NACIONALIDAD != 'ESCOCESA' AND NACIONALIDAD != 'BRITANICA';

/*6*/
SELECT C.PROPIETARIO, C.NOMBRE FROM CABALLOS C, PERSONAS P
WHERE P.CODIGO = C.PROPIETARIO AND
(C.FECHANACIMIENTO =TO_DATE('11','MM') OR C.PESO>260)
ORDER BY P.CODIGO DESC, C.NOMBRE ASC;

/*7*/
SELECT DISTINCT NOMBRE FROM PERSONAS
WHERE NOMBRE LIKE UPPER('J%') AND NOMBRE LIKE LOWER('%E%');

/*8*/
/*A*/
    SELECT DISTINCT C.CODCABALLO, SUM(P.POSICIONFINAL) FROM CABALLOS C, PARTICIPACIONES P
    WHERE C.CODCABALLO = P.CODCABALLO AND P.POSICIONFINAL = 1 GROUP BY C.CODCABALLO;

/*B*/
    SELECT P.CODCABALLO FROM PARTICIPACIONES P
    WHERE P.POSICIONFINAL = 1
    GROUP BY P.CODCABALLO
    HAVING COUNT(*) > 1;

/*9*/
SELECT MAX(IMPORTEPREMIO) FROM CARRERAS;

/*10*/
SELECT MAX(a.IMPORTE) FROM APUESTAS a, CLIENTES c
WHERE C.DNI = A.DNICLIENTE;

/*11*/
SELECT c.NOMBRE, a.IMPORTE AS DINERO_GANADO FROM CLIENTES c, APUESTAS a
WHERE c.DNI = a.DNICLIENTE;

/*12*/
SELECT P.NOMBRE, P.APELLIDOS, C.NOMBRE AS NOMBRE_CABALLO FROM PERSONAS P, PARTICIPACIONES PA, CABALLOS C
WHERE P.CODIGO = PA.JOCKEY AND PA.CODCABALLO = C.CODCABALLO AND PA.POSICIONFINAL = 1;

/*13 */
SELECT DISTINCT P.NOMBRE, P.APELLIDOS FROM PERSONAS P, PARTICIPACIONES PA
WHERE P.CODIGO = PA.JOCKEY;

/*14*/
SELECT C.NOMBRECARRERA, CL.NOMBRE, A.IMPORTE FROM CARRERAS C, CLIENTES CL, APUESTAS A
WHERE C.CODCARRERA = A.CODCARRERA AND CL.DNI = A.DNICLIENTE AND A.IMPORTE > C.APUESTALIMITE;

/*15 */
SELECT P.NOMBRE, P.APELLIDOS, C.NOMBRE AS NOMBRE_CABALLO FROM PERSONAS P, CABALLOS C
WHERE P.CODIGO = C.PROPIETARIO GROUP BY P.NOMBRE, P.APELLIDOS, C.NOMBRE HAVING COUNT(*) > 2;

/*16*/
SELECT DISTINCT C.NOMBRE, C.NACIONALIDAD FROM CLIENTES C, APUESTAS A
WHERE C.DNI = A.DNICLIENTE AND A.IMPORTE > 800;



